import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff
import networkx as nx
from sklearn.decomposition import PCA
from sklearn.cross_decomposition import PLSRegression
from sklearn.ensemble import RandomForestClassifier, IsolationForest
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from scipy.cluster.hierarchy import linkage
from fpdf import FPDF
import base64
import warnings
warnings.filterwarnings('ignore')

st.set_page_config(page_title="Executive Botanical AI", layout="wide")

# --- Power BI Inspired CSS ---
st.markdown("""
<style>
div[data-testid="metric-container"] {
    background-color: rgba(28, 30, 33, 0.5);
    border: 1px solid rgba(255, 255, 255, 0.1);
    padding: 5% 5% 5% 10%;
    border-radius: 8px;
    border-left: 6px solid #5E33BF;
    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
}
</style>
""", unsafe_allow_html=True)

# --- Mathematical VIP Extraction ---
def calculate_vips(model):
    t = np.nan_to_num(model.x_scores_)
    w = np.nan_to_num(model.x_weights_)
    q = np.nan_to_num(model.y_loadings_)
    p, h = w.shape
    vips = np.zeros((p,))
    s = np.diag(t.T @ t) * np.diag(q.T @ q) 
    total_s = np.sum(s) if np.sum(s) > 1e-10 else 1e-10 
    
    for i in range(p):
        weight = np.array([ (w[i,j] / (np.linalg.norm(w[:,j]) + 1e-10))**2 for j in range(h) ])
        vips[i] = np.sqrt(p * (s @ weight) / total_s)
    return np.nan_to_num(vips)

# --- PDF Certificate of Analysis Generator ---
def create_coa_pdf(batch_id, status, is_anomalous, profile_dict):
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", 'B', 18)
    pdf.set_text_color(94, 51, 191) # Purple branding
    pdf.cell(0, 10, "CERTIFICATE OF ANALYSIS (CoA)", ln=True, align='C')
    pdf.set_font("Arial", 'I', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, "Automated Chemometric AI Quality Control", ln=True, align='C')
    pdf.ln(10)
    
    # Batch Info
    pdf.set_font("Arial", 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(50, 10, "Batch Reference:", border=1)
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 10, f" {batch_id}", border=1, ln=True)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(50, 10, "QC Decision:", border=1)
    pdf.set_font("Arial", 'B', 12)
    pdf.set_text_color(0, 150, 0) if "Authentic" in status else pdf.set_text_color(200, 0, 0)
    pdf.cell(0, 10, f" {status}", border=1, ln=True)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(50, 10, "Anomaly Status:", border=1)
    pdf.set_font("Arial", 'B', 12)
    pdf.set_text_color(200, 0, 0) if is_anomalous else pdf.set_text_color(0, 150, 0)
    pdf.cell(0, 10, " FLAGGED (Isolation Forest)" if is_anomalous else " PASS (Baseline)", border=1, ln=True)
    pdf.ln(10)
    
    # Phytochemical Profile
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Phytochemical Integration Profile", ln=True)
    pdf.set_font("Arial", 'B', 10)
    pdf.cell(100, 8, "Terpene / Biomarker", border=1)
    pdf.cell(0, 8, "Relative Peak Area (mAU)", border=1, ln=True)
    
    pdf.set_font("Arial", '', 10)
    for terpene, area in profile_dict.items():
        pdf.cell(100, 8, terpene, border=1)
        pdf.cell(0, 8, f"{area:.2f}", border=1, ln=True)
        
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, "Generated by Enterprise AI Botanical Fingerprinter.", align='C')
    
    return pdf.output(dest='S').encode('latin-1')

# --- Synthetic Data Generation ---
@st.cache_data
def generate_gcms_data():
    np.random.seed(42)
    terpenes = ['Linalool', 'Geraniol', 'Limonene', 'Carvacrol', 'Thymol', 'a-Pinene', 'b-Pinene', 'Eucalyptol', 'Camphor', 'Terpinen-4-ol']
    data, labels = [], []
    
    for _ in range(60): 
        data.append(np.random.normal(loc=[40, 30, 5, 2, 1, 10, 8, 2, 1, 1], scale=2))
        labels.append("Origin A (Authentic)")
        
    for _ in range(60): 
        data.append(np.random.normal(loc=[10, 15, 35, 1, 1, 20, 15, 1, 1, 1], scale=2))
        labels.append("Origin B (Authentic)")
        
    for _ in range(25): 
        data.append(np.random.normal(loc=[80, 5, 5, 1, 1, 2, 2, 2, 0.5, 0.5], scale=5))
        labels.append("Adulterated (Rejected)")
        
    df = pd.DataFrame(data, columns=terpenes)
    df = np.clip(df, 0.001, None) 
    df = df.replace([np.inf, -np.inf], np.nan).fillna(0.001)
    df['Batch_Class'] = labels
    df.insert(0, 'Batch_ID', [f"BATCH-{i:04d}" for i in range(len(df))])
    return df, terpenes

# --- UI Setup ---
st.title("🌿 Executive AI Botanical Fingerprinter")
st.markdown("Industrial multivariate GCxGC-MS pipeline integrating LIMS Reporting, XAI, and Power BI-style schematic architecture.")

df, features = generate_gcms_data()

st.sidebar.header("Data Ingestion Pipeline")
uploaded_file = st.sidebar.file_uploader("Upload GC-MS Peak Matrix (CSV)", type=['csv'])

if uploaded_file:
    df = pd.read_csv(uploaded_file)
    df = df.replace([np.inf, -np.inf], np.nan).fillna(0.001)
    features = [col for col in df.columns if col not in ['Batch_Class', 'Batch_ID']]
else:
    st.sidebar.info("Demo Mode: Synthesizing Industrial GC-MS Terpene Profiles.")

X = df[features].values
y_labels = df['Batch_Class'].values
scaler = StandardScaler()
X_scaled = np.nan_to_num(scaler.fit_transform(X))

st.sidebar.markdown("---")
st.sidebar.header("Hyperparameters")
n_components = st.sidebar.slider("Latent Components", 2, 5, 3)
contamination = st.sidebar.slider("Expected Adulteration Rate", 0.01, 0.30, 0.10, 0.01)

# PBI Metrics
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Batches Scanned", len(df))
col2.metric("Tracked Phytochemicals", len(features))
auth_count = list(y_labels).count("Origin A (Authentic)") + list(y_labels).count("Origin B (Authentic)")
col3.metric("Authentic Batches", auth_count)
col4.metric("Flagged Adulterations", len(df) - auth_count, delta=f"{(1 - (auth_count/len(df)))*100:.1f}% Reject Rate", delta_color="inverse")

tab_exploratory, tab_vips, tab_network, tab_xai, tab_lims = st.tabs(["🌌 GCxGC Space & Biplots", "🧬 Biomarkers (PLS-DA)", "🕸️ Phyto-Network", "🤖 Explainable AI QC", "📑 LIMS CoA Generator"])

with tab_exploratory:
    c1, c2 = st.columns([1.5, 1])
    with c1:
        pca = PCA(n_components=n_components)
        scores = pca.fit_transform(X_scaled)
        loadings = pca.components_.T * np.sqrt(pca.explained_variance_)
        var_explained = pca.explained_variance_ratio_ * 100
        
        fig_biplot = px.scatter(x=scores[:,0], y=scores[:,1], color=y_labels, title="PCA Biplot (Scores & Feature Loadings)",
                                labels={'x': f'PC1 ({var_explained[0]:.1f}%)', 'y': f'PC2 ({var_explained[1]:.1f}%)'})
        for i, feature in enumerate(features):
            fig_biplot.add_shape(type='line', x0=0, y0=0, x1=loadings[i, 0]*4, y1=loadings[i, 1]*4, line=dict(color='cyan', width=1, dash='dot'))
            fig_biplot.add_annotation(x=loadings[i, 0]*4.2, y=loadings[i, 1]*4.2, text=feature, showarrow=False, font=dict(color='cyan'))
        fig_biplot.update_layout(margin=dict(l=0, r=0, b=0, t=40))
        st.plotly_chart(fig_biplot, use_container_width=True)
        
    with c2:
        Z = linkage(X_scaled, method='ward', metric='euclidean')
        fig_dendro = ff.create_dendrogram(X_scaled, labels=y_labels, orientation='left', color_threshold=15)
        fig_dendro.update_layout(width=600, height=500, margin=dict(l=0, r=0, b=0, t=40), xaxis_title="Euclidean Distance", yaxis_title="Batch", title="HCA Dendrogram")
        st.plotly_chart(fig_dendro, use_container_width=True)

with tab_vips:
    y_encoded = pd.get_dummies(y_labels).values 
    pls_model = PLSRegression(n_components=n_components)
    pls_model.fit(X_scaled, y_encoded)
    
    c1, c2 = st.columns([1.5, 1])
    with c1:
        vips = calculate_vips(pls_model)
        vip_df = pd.DataFrame({'Phytochemical': features, 'VIP Score': vips}).sort_values('VIP Score', ascending=True)
        fig_vip = px.bar(vip_df, x='VIP Score', y='Phytochemical', orientation='h', color='VIP Score', color_continuous_scale='Magma', title="Variable Importance in Projection (VIP)")
        fig_vip.add_vline(x=1.0, line_dash="dash", line_color="cyan", annotation_text="Significance (>1.0)")
        st.plotly_chart(fig_vip, use_container_width=True)
    with c2:
        if 'Linalool' in df.columns and 'Geraniol' in df.columns:
            df['Lin/Ger Ratio'] = df['Linalool'] / df['Geraniol']
            fig_ratio = px.box(df, x="Batch_Class", y="Lin/Ger Ratio", color="Batch_Class", title="Key Quality Ratio Matrix")
            st.plotly_chart(fig_ratio, use_container_width=True)

with tab_network:
    corr_matrix = df[features].corr().values
    G = nx.Graph()
    for i in range(len(features)):
        G.add_node(features[i])
        for j in range(i+1, len(features)):
            if corr_matrix[i, j] > 0.4: 
                G.add_edge(features[i], features[j], weight=corr_matrix[i, j])
                
    pos = nx.spring_layout(G, seed=42)
    edge_x, edge_y = [], []
    for edge in G.edges():
        edge_x.extend([pos[edge[0]][0], pos[edge[1]][0], None])
        edge_y.extend([pos[edge[0]][1], pos[edge[1]][1], None])

    fig_net = go.Figure()
    fig_net.add_trace(go.Scatter(x=edge_x, y=edge_y, mode='lines', line=dict(width=1, color='#888'), hoverinfo='none'))
    fig_net.add_trace(go.Scatter(x=[pos[n][0] for n in G.nodes()], y=[pos[n][1] for n in G.nodes()], mode='markers+text', text=list(G.nodes()), textposition="top center",
                                 marker=dict(showscale=True, colorscale='YlGnBu', size=20, color=[G.degree(n) for n in G.nodes()], line_width=2)))
    fig_net.update_layout(showlegend=False, xaxis=dict(showgrid=False, zeroline=False, showticklabels=False), yaxis=dict(showgrid=False, zeroline=False, showticklabels=False), margin=dict(l=0, r=0, b=0, t=0))
    st.plotly_chart(fig_net, use_container_width=True)

with tab_xai:
    rf = RandomForestClassifier(n_estimators=100, random_state=42)
    rf.fit(X_scaled, y_labels)
    iso_forest = IsolationForest(contamination=contamination, random_state=42)
    anomalies = iso_forest.fit_predict(X_scaled)
    df['Anomaly'] = anomalies
    
    authentic_indices = [i for i, y in enumerate(y_labels) if "Authentic" in y]
    auth_mean = X_scaled[authentic_indices].mean(axis=0) if authentic_indices else np.zeros(X_scaled.shape[1])
    
    anomalous_indices = [i for i, status in enumerate(anomalies) if status == -1]
    if anomalous_indices:
        sample_idx = anomalous_indices[0]
        st.error(f"🚨 **Batch {df.iloc[sample_idx]['Batch_ID']} Flagged by Isolation Forest (Zero-Shot Anomaly Detection)**")
        
        impact = (X_scaled[sample_idx] - auth_mean) * rf.feature_importances_
        waterfall_df = pd.DataFrame({'Terpene': features, 'Impact': impact}).sort_values('Impact', ascending=False)
        
        fig_water = go.Figure(go.Waterfall(
            name="Adulteration Drivers", orientation="h", y=waterfall_df['Terpene'], x=waterfall_df['Impact'],
            textposition="outside", text=[f"{v:.2f}" for v in waterfall_df['Impact']], connector={"line":{"color":"rgb(63, 63, 63)"}}
        ))
        fig_water.update_layout(title="Root Cause Analysis: Specific Phytochemicals Triggering Rejection", showlegend=False, height=450)
        st.plotly_chart(fig_water, use_container_width=True)

with tab_lims:
    st.subheader("Automated Certificate of Analysis (CoA) Generation")
    st.markdown("Select a processed batch to generate a downloadable, audit-ready PDF report detailing its QC status and phytochemical profile.")
    
    batch_options = df['Batch_ID'].tolist()
    selected_batch = st.selectbox("Select Batch ID", batch_options)
    
    if selected_batch:
        batch_row = df[df['Batch_ID'] == selected_batch].iloc[0]
        batch_idx = df.index[df['Batch_ID'] == selected_batch][0]
        
        c1, c2 = st.columns(2)
        with c1:
            st.metric("QC Decision", batch_row['Batch_Class'])
        with c2:
            st.metric("Anomaly Flag", "FLAGGED" if batch_row['Anomaly'] == -1 else "PASS")
            
        profile_dict = {f: batch_row[f] for f in features}
        
        pdf_bytes = create_coa_pdf(
            batch_id=selected_batch,
            status=batch_row['Batch_Class'],
            is_anomalous=(batch_row['Anomaly'] == -1),
            profile_dict=profile_dict
        )
        
        st.download_button(
            label="📥 Download Certificate of Analysis (PDF)",
            data=pdf_bytes,
            file_name=f"CoA_{selected_batch}.pdf",
            mime="application/pdf"
        )